// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slaeuuevaunzkhwcknnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYWV1dWV2YXVuemtod2Nrbm5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzIyNTgsImV4cCI6MjA1ODA0ODI1OH0.JlpW_NOyBcILB1xEzofwPopTPQVtNRdIKXVnoQMXCIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);